name: chatbot_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.1.0
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_facebook_auth: ^7.1.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  get_it: ^8.0.2
  google_generative_ai: ^0.4.6
  google_sign_in: ^6.2.2
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  video_player: ^2.9.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_intl:
  enabled: true
